brew "git"
brew "ripgrep"
brew "fd"
brew "bat"
brew "zoxide"
brew "atuin"
brew "eza"
brew "sd"
brew "fzf"
brew "jq"
brew "gh"
brew "lazygit"
brew "lazydocker"
brew "direnv"
brew "node"
brew "codex"
brew "pnpm"
tap "oven-sh/bun"
brew "oven-sh/bun/bun"
brew "fish"

cask "raycast"
cask "rectangle"
cask "chatgpt"
cask "1password"
cask "font-hack-nerd-font"
cask "ghostty"
cask "discord"
cask "spotify"
cask "tableplus"
cask "maccy"
cask "zed"

hostname = `hostname`.strip
if hostname == "koichiro-mac-work"
  brew "azure-cli"

  cask "dotnet-sdk@8"
  cask "gather"
  cask "jetbrains-toolbox"
  cask "linqpad"
  cask "microsoft-azure-storage-explorer"
  cask "notion"
  cask "powershell"
  cask "visual-studio-code"
else
  cask "orbstack"
  cask "brave-browser"
end
